### ISSUE TITLE
Make a defined stable "API" for extensions/scripts/etc. to click to go to the original page 

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/github-wiki-see-rs#138]
Example: https://github.com/nelsonjchen/github-wiki-see-rs/issues/136#issuecomment-1040821971

**Comment by nelsonjchen** [comment]
@gingerbeardman

I think I've defined the API. Let me know if you have any comments. I just used your example and pledged to it in https://github.com/nelsonjchen/github-wiki-see-rs/blob/master/AUTO_REDIRECT_API.md and linked it from the front page.

**Comment by nelsonjchen** [comment]
@gingerbeardman

I just realized. Does your back button work? Or does it get jammed going back? I took out the window.replace so this might be an issue.

**Comment by gingerbeardman** [comment]
I'll check soon

**Comment by nelsonjchen** [comment]
```javascript
if (document.getElementById('header_button'))
    window.location.replace(document.querySelector(".visit_url_button").href);
```

I think this might work better.

**Comment by nelsonjchen** [comment]
That seems to work in my testing in Safari. @gingerbeardman you should update your script with that. Let me know if you other comments.
