### ISSUE TITLE
Additionally use Cloudflare Workers to check if GitHub permits indexing before loading the proxied page

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/github-wiki-see-rs#160]
Preliminary tests seem to indicate this can handle the load whereas the "origin" server cannot implement this.

**Comment by nelsonjchen** [comment]
Implemented. We'll see the costs.

**Comment by nelsonjchen** [comment]
@austintraver Please let me know if you see a search result from GHWSEE atop GitHub again and it isn't a 308 redirect. This should address that issue continually.

**Comment by austintraver** [comment]
> @austintraver Please let me know if you see a search result from GHWSEE atop GitHub again and it isn't a 308 redirect. This should address that issue continually.

@nelsonjchen You did it! This change seems to have done the trick. Here are the top search results I see when searching for `ideavim sethandler` (First mentioned in https://github.com/arosh/ublacklist-github-translation/pull/21).

![search result](https://user-images.githubusercontent.com/25112463/158056560-a7f4a23d-e1e2-45cc-a0d0-5b94470ff716.jpeg)

Thank you for taking the time to address this! Bookmarking GHWSEE, looks useful! 😃

**Comment by nelsonjchen** [comment]
I think I updated the burned in decommission list like a few days after you made that PR. GitHub is/was changing their criteria so it kind of was lagging behind. Getting off Google selectively is hard and hilariously they don't make an API for the search console. There's all sorts of screen scrapy paid solutions that were kind of beyond the weekend warrior nature of this project for that.
