### ISSUE TITLE
"View Page On GitHub" button is too big and flashy, or looks too much like a logo, triggering banner blindness

### ISSUE THREAD

**Issue by tbodt** [nelsonjchen/github-wiki-see-rs#281]
Speaking from personal experience here...whenever I find myself on one of these pages, my mind completely skips over the big blue button, and instead I hunt for the tiny link below it with the "URL" label. It would be much better, I think, to put it a bit lower so it doesn't look like a logo.

**Comment by nelsonjchen** [comment]
OK, I'll give something a try. I think I was pretty desperate to make it prominent because people kept ignoring it but too much had an opposite effect.

**Comment by nelsonjchen** [comment]
Fiddled with it a bit.

**Comment by nelsonjchen** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/5363/188720545-596a1878-e8ac-4a05-8cdf-41168802d23b.png">

**Comment by tbodt** [comment]
Not entirely sure if it's better...

What might be a good idea is to style the top section so it has a height of 100%. Then my eyes couldn't skip directly to the content. Also my gut says it's detrimental for the button to be taller than about two lines of text.

**Comment by nelsonjchen** [comment]
Ah, I don't style the top section to that great of a height because I'm kind of worried some search engines may see that as hiding the content or cloaking. 

I'll keep fiddling with the button size.

**Comment by tbodt** [comment]
Maybe it would make sense to remove the button and give the url the same styling as the button (though keeping its size).

I gotta say though, the low quality of the web design makes this feel like the most trustworthy site i've visited in a while :D

**Comment by nelsonjchen** [comment]
It's definitely polarizing. I think I've gotten comments that it looks like a scam. I suspect those reports are from people who get reamed by the flashy designs of crypto.com or coinbase.com or whatever flashy design rug pull operations are using.

**Comment by nelsonjchen** [comment]
I actually left it so badly designed because all the other GitHub "mirrors"/seo-farm had fancy designs that could be called designs. If it wasn't so badly designed, it couldn't stand out from those other ones and have a chance to be evaluated for trustworthiness.

**Comment by nelsonjchen** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/5363/188759805-f00d092b-28f5-41cb-b4f8-861cb17d2002.png">

I'm going to let it be for now. The button is there as a statement to express the intent of the service more anyway, even if some users use or prefer the explicit URL portion more day-to-day reflexively. However your brain is wired, I think the design is now better for both.

**Comment by tbodt** [comment]
👍 I'd call this an improvement
